### ISSUE TITLE
Problem with a chat

### ISSUE THREAD

**Issue by ZeralldMC** [AuroraUniverse/AuroraUniverse#6]
The problem is that when i write in the chat, i get a message like this:
![image](https://user-images.githubusercontent.com/115047953/232306924-5383376f-6f2d-47e9-8f08-cbf9433830b1.png)
While the tab has excellent placeholders from lp:
![image](https://user-images.githubusercontent.com/115047953/232306955-90efd649-5795-4cd1-8de1-8db8f7fb10af.png)
I don't know what the problem is exactly, but maybe I can back up the language file here for more details? I hasten to assume that this is my problem and I have something wrong, but I think you can help me. By the way, your discord link is inactive...
I must say that I use the usual config russian.yaml, but with changed variables in the chat, that's all.
Thanks you for the help

**Comment by karlovm** [comment]
By default, the language file uses LuckPerms placeholders. If you have not LuckPerms plugin installed, you may just remove this placeholders in russian.yml.

If you are using LuckPerms, download LuckPermis placeholder extension using /papi command.
