### ISSUE TITLE
auneco disabling 

### ISSUE THREAD

**Issue by ZeralldMC** [AuroraUniverse/AuroraUniverse#7]
Is there any way to disable auneco? I already have a plugin for XConomy

**Comment by karlovm** [comment]
Unfortunately, AuroraUniverse currently not supporting another economy plugins

**Comment by ZeralldMC** [comment]
> Unfortunately, AuroraUniverse currently not supporting another economy plugins
Good, it's even better. Do you have a list of placeholders for tab to display the balance in it?
