### ISSUE TITLE
how to turn on the display of territories?

### ISSUE THREAD

**Issue by Cursed1234** [AuroraUniverse/AuroraUniverse#8]
![image](https://github.com/AuroraUniverse/AuroraUniverse/assets/80481907/74988313-9929-4665-be6c-c48ebab2d4bf)
![image](https://github.com/AuroraUniverse/AuroraUniverse/assets/80481907/c2007069-0809-402d-917b-1de20c28f829)
i write 'true' on this line but not working

**Comment by karlovm** [comment]
Do you have AuroraDynmap installed?

**Comment by Cursed1234** [comment]
yeah

**Comment by karlovm** [comment]
Try to claim more than 1 chunk

**Comment by Cursed1234** [comment]
ok

**Comment by Cursed1234** [comment]
> Try to claim more than 1 chunk


i cant attach chunk, it say "Unable to attach chunk"

**Comment by karlovm** [comment]
Just deposit by /t deposit

**Comment by Cursed1234** [comment]
> Just deposit by /t deposit

thx, u help me.
i have 1 question, how to off global chat?

**Comment by karlovm** [comment]
There is chat ignore command

**Comment by Cursed1234** [comment]
> There is chat ignore command

which

**Comment by Cursed1234** [comment]
> /chart ignore

thanks
